s1_reprojected_dir: 'assets/data/sentinel_data/s1_reprojected'
s2_reprojected_dir: 'gee_data_reprojected/'
gt_dir: 'assets/data/preprocessed'
split_mask_dir: 'assets/data/split_masks'
save_dir: 'data/TEST_avg_cldprb_25-50'
name: 'avg_cldprb_25-50'
project_shapefiles: ['assets/data/NHM_projectDekning_AOI_edit2015_V2.shp', 'assets/data/ALS_projects_Dz_all_norway.shp']
data_bands: [1, 2, 3, 4, 5] # p95, mean height, density, gini, cover
projects: ['1023']
sampling_strategy: 's2_offset_valid_center'
patch_size: 15