s1_reprojected_dir: 'assets/data/sentinel_data/s1_reprojected'
s2_reprojected_dir: 'assets/data/sentinel_data/s2_reprojected'
gt_dir: 'assets/data/preprocessed'
split_mask_dir: 'assets/data/split_masks'
save_dir: 'data/cp_retraining'
name: 'empirical_cloud_threshold_exp_30'
project_shapefiles: ['assets/data/NHM_projectDekning_AOI_edit2015_V2.shp', 'assets/data/ALS_projects_Dz_all_norway.shp']
data_bands: [1, 2, 3, 4, 5] # p95, mean height, density, gini, cover
projects: ['1023', '825', '764']
sampling_strategy: 'valid_center'
patch_size: 15
testset_max_days_delta: 365 # restrict testset to "cleanest" version, i.e. with diff between images and gt of max x days
cloud_prob_threshold: 30
cloudy_pixels_threshold: 0.01
add_date_to_save_dir: false
