s1_reprojected_dir: 'assets/data/sentinel_data/s1_reprojected'
s2_reprojected_dir: 'gee_data/empirical_cloud_threshold_exp/${imageId}'
gt_dir: 'assets/data/preprocessed'
split_mask_dir: null
save_dir: 'data/empirical_cloud_threshold_exp/${now}_empirical_cloud_threshold_exp_70_gee/${imageId}'
name: null
project_shapefiles: ['assets/data/NHM_projectDekning_AOI_edit2015_V2.shp', 'assets/data/ALS_projects_Dz_all_norway.shp']
data_bands: [1, 2, 3, 4, 5] # p95, mean height, density, gini, cover
projects: ['1023', '825', '764']
sampling_strategy: 's2_offset_valid_center'
patch_size: 15
stats_path: 'data/empirical_cloud_threshold_exp/2023-07-28_15-54-42_empirical_cloud_threshold_exp_70/stats.yaml'
