datasets: # created datasets
  albecker_stable: 'assets/data/pkl/2021-05-18_10-57-45'
  baseline_365days: 'data/2023-04-05_18-58-33_baseline'

results: # predictions and evaluation
  baseline_365days: 'results/2023-04-06_10-52-04_baseline'

