s1_reprojected_dir: 'data/sentinel_data/s1_reprojected'
s2_reprojected_dir: 'data/sentinel_data/s2_reprojected'
gt_dir: 'data/preprocessed'
split_mask_dir: 'data/split_masks'
save_dir: 'data/pkl_dev'
project_shapefiles: ['data/NHM_projectDekning_AOI_edit2015_V2.shp']
data_bands: [1, 2, 3, 4, 5] # p95, mean height, density, gini, cover
projects: ["827", "920"]
sampling_strategy: 'valid_center'
patch_size: 15
cloud_prob_threshold: 10
cloudy_pixels_threshold: 0.1