projects: ["498"]
verbose: true
data:
  gt_dir: "assets/data/preprocessed"
  gt_data_bands: [1, 2, 3, 4, 5]
  shapefile_paths: ['assets/data/NHM_projectDekning_AOI_edit2015_V2.shp', 'assets/data/ALS_projects_Dz_all_norway.shp']
  target_crs: "EPSG:4326"
gee:
  token_file: "token.json"
  credentials_file: "credentials.json"
  gdrive_scopes: ["https://www.googleapis.com/auth/drive"]
  # GEE parameters
  gee_project: "ee-walteliot"
  crs: "EPSG:4326"
timeserie:
  # timeseries parameters
  localdir: "gee_data"
  date_offset_amount: 180
  date_offset_unit: "day"
  date_offset_policy: "both" # (before, after, both)
  collection_name: "COPERNICUS/S2_SR_HARMONIZED"
  s2_bands: ['B1','B2','B3','B4','B5','B6','B7','B8','B8A', 'B9', 'B11','B12','MSK_CLDPRB']
  drivefolder: "geeExports"
  batch: false # if false, sequential dl o/w parallel
  agg: null # if None, raw images, o/w compute agg
  mosaic: false # if True mosaic same dates
  dtype: "uint16"
  scale: 10