project_id: "498"
gt_dir: "assets/data/preprocessed"
gt_data_bands: [1, 2, 3, 4, 5]
shapefile_paths: ['assets/data/NHM_projectDekning_AOI_edit2015_V2.shp', 'assets/data/ALS_projects_Dz_all_norway.shp']
localdir: "gee_data/"
date_offset_amount: 180
drivefolder: "geeExports"