s1_reprojected_dir: 'assets/data/sentinel_data/s1_reprojected'
s2_reprojected_dir: 'gee_data/reprojected_dirs/${imageId}'
gt_dir: 'assets/data/preprocessed'
split_mask_dir: null
project_shapefiles: ['assets/data/NHM_projectDekning_AOI_edit2015_V2.shp', 'assets/data/ALS_projects_Dz_all_norway.shp']
data_bands: [1, 2, 3, 4, 5] # p95, mean height, density, gini, cover
projects: ['1023', '825', '764']
sampling_strategy: 's2_offset_valid_center'
patch_size: 15
margin: 3  # should be less than 7 to not overlap with train/val stripes
pkl_dir: 'data/empirical_cloud_threshold_exp/${now}_empirical_cloud_threshold_exp_70_gee/${imageId}'
save_dir: 'results/empirical_cloud_threshold_exp/${now}_empirical_cloud_threshold_exp_70_gee/${imageId}'
name: null
closest_s1: true
add_date_to_save_dir: false
checkpoint_dirs: # c
  - 'train_logs/23-07-31_11-15-03_noisy-manatee-49'
  - 'train_logs/23-07-31_11-15-00_rugged-falcon-48'
  - 'train_logs/23-07-31_11-14-59_super-tarsier-47'
  - 'train_logs/23-07-31_11-14-59_silent-pig-47'
  - 'train_logs/23-07-31_11-14-58_silver-orangutan-46'
